### ISSUE TITLE
ユーザがパスワードでログインできるようにCognitoのexplicit_auth_flowsを変更

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/kimono-app-terraform#10]
# Doneの定義
- ユーザがパスワードでログインできること

# 補足

ユーザ名とパスワードでログインする際に、下記のエラーが発生した。
開発を進めるために、explicit_auth_flowsに`ALLOW_USER_PASSWORD_AUTH`を追加する。
```
USER_PASSWORD_AUTH flow not enabled for this client
```

**Comment by kobayashi-m42** [comment]
@keitakn ポイントは1くらいかな？

**Comment by keitakn** [comment]
@kobayashi-m42 そうだね！1で大丈夫だと思う🐱！
