### ISSUE TITLE
SESのリージョンを東京リージョンに変更する

### ISSUE THREAD

**Issue by keitakn** [nekochans/kimono-app-terraform#12]
# Doneの定義
- 表題の件が実施されている事

# 補足情報
最近東京リージョンで利用出来るようになった模様、しかし明確なメリットがないのであれば既存のままでも良いかも？

Cognitoのメール送信処理はSESを使っているので、メールの到達送信速度とか少しは変わるのだろうか？ただ東京リージョン一本に絞れるので構成管理はスッキリしそう！

https://dev.classmethod.jp/articles/new-available-amazon-ses-tokyo-region/

**Comment by kobayashi-m42** [comment]
PRのコメントにも記載したが、CognitoでSESを使用できるリージョンに東京リージョンは含まれていない。

> Amazon SES で使用できるリージョンは、米国東部 (バージニア北部) us-east-1、米国西部 (オレゴン) us-west-2、および欧州 (アイルランド) eu-west-1 です。

https://docs.aws.amazon.com/ja_jp/cognito/latest/developerguide/user-pool-email.html

@keitakn 
CognitoでSESを使用することを前提としているため、この課題は対応できないためこのままクローズしようと思う！

**Comment by keitakn** [comment]
@kobayashi-m42 

>PRのコメントにも記載したが、CognitoでSESを使用できるリージョンに東京リージョンは含まれていない。

なるほど、これは盲点だったね、、、ありがとう！クローズでおｋ🐱！
