### ISSUE TITLE
APIGatewayの仕組みに認可の概念を導入する

### ISSUE THREAD

**Issue by keitakn** [nekochans/kimono-app-terraform#15]
# Doneの定義
- APIGatewayのユーザー毎に適切な権限が付与された状態になっている事

https://github.com/nekochans/kimono-app/issues/2#issuecomment-636429148 に書いてある通り、ユーザーが別のユーザーの情報にアクセス（個人情報はNGだけどパブリックな情報はOK）したり、他のユーザーの情報を書き換えたりする事が出来ないようになっている必要がある。

# 補足情報
https://github.com/nekochans/kimono-app-terraform/issues/14 を先に終わらせておく必要がある。

**Comment by keitakn** [comment]
これやる前にバックエンドのAPIに適当なユーザー情報を取得するようなエンドポイントを用意しておく必要がある。

**Comment by keitakn** [comment]
// アクセストークンA 参照系API呼べます、ただし個人情報の参照に関してはユーザーID 1000のリソースにしかアクセス出来ない
```
{
  "token": "aaaaaa",
  "scopes": ['read_qiita'],
  "sub": 1000
}
```

// アクセストークンB 参照系・更新系API呼べます、ただし個人情報の参照・更新に関してはユーザーID 1000のリソースにしかアクセス出来ない
```
{
  "token": "bbbb",
  "scopes": ['read_qiita', 'write_qiita'],
  "sub": 1000
}
```

例えばアクセストークンAの場合は↓がIAMポリシーに設定すべきリソースという事になる。

```
const resource = [
  '/GET/account/v1/users/*/public-info',
  '/HEAD/account/v1/users/*/public-info',
  '/GET/account/v1/users/1000/addresses',
  '/HEAD/account/v1/users/1000/addresses',
  '/GET/account/v1/users/1000/workplaces',
  '/HEAD/account/v1/users/1000/workplaces',
];
```

https://www.authlete.com/developers/custom_authorizer/

**Comment by keitakn** [comment]
https://qiita.com/keitakn/items/508744fe7dc3b5f75d4c

**Comment by keitakn** [comment]
# めも

API Gateway 「HTTP API」の場合、JWT Authorizersを利用する必要がある🐱

https://dev.classmethod.jp/articles/amazon-api-gateway-jwt-authorizers/

https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-jwt-authorizer.html

やってみないと分からないが、Custom Authorizerと違ってこれだけだと https://github.com/nekochans/kimono-app-terraform/issues/15#issuecomment-657182757 に書いてある事が実現出来ない可能性がある、その場合は↓

1. API Gatewayの呼び出し（JWTトークン付きで）
2. API GatewayのJWT AuthorizersでJWTを検証（この時点でJWTが不正ならAPI Gatewayが403を返してくれるはず）
3. API Gatewayから直接APIを呼び出すのではなくLambda関数を呼び出す、このLambdaの中でJWTのscopeに合わせてAPIを呼び出して良いか確認、駄目なら403を返す
4. 3でAPI呼び出し可能と判断した場合のみ、バックエンドのAPIにLambdaから通信を行う

という流れが必要かもしれない、HTTP APIでもLambdaを呼び出す事が可能なハズなのでこの流れで行けるハズ！

**Comment by keitakn** [comment]
@kobayashi-m42 

実装方法の案をまとめてみた！🐱

- [kimono-api認証認可（Lambdaを使う場合） A案](https://gist.github.com/keitakn/f9207584390f6ff5f7aaf01b492f1695)
- [kimono-api認証認可（Goの自作Packageを使う場合）B案](https://gist.github.com/keitakn/8be1a281926d0f5ac49d560e1a7177ab)

Lambdaを使う場合とGoの自作Packageを使う場合だけど両方ともこの中でやるのは https://github.com/nekochans/kimono-app-terraform/issues/15#issuecomment-657182757 の内容になるよ！

あとはAPIの各機能はcognitoのCustomScopeとして登録すれば良いかなと思っていて（この記事にあるようにリソースサーバーの登録）↓

https://qiita.com/nannany_tis/items/52d322be4522a2a8f3f9

scope名は難しいけど、最終的に課金しないと使えない機能とかも増えるかもだし、一般会員と課金済会員とかにしておけば良いかなと思ってる！

ちなみに個人的にはB案押しかなーと思うけどどうだろう？？

**Comment by keitakn** [comment]
# Next Action memo

- cognitoにリソースサーバーとスコープを追加する（issue作成） 5
- バックエンドAPIの中で認可処理を作成する（issue作成） 21
- バックエンドAPIの認可処理部分を別Packageに切り出す（Gitリポジトリ作成 + issue作成） 8

**Comment by kobayashi-m42** [comment]
@keitakn 
下記の課題に分割したので、この課題はクローズするね！
https://github.com/nekochans/kimono-app-terraform/issues/23
https://github.com/nekochans/kimono-app-api/issues/17
https://github.com/nekochans/kimono-app-api/issues/18

**Comment by keitakn** [comment]
@kobayashi-m42 https://github.com/nekochans/kimono-app-terraform/issues/15#issuecomment-667790498 了解！ありがとう👍
