### ISSUE TITLE
リソース名の指定が間違っておりterraform applyで失敗する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/kimono-app-terraform#18]
# 概要
表題の通り

# 再現手順
`13-ses`の作業ディレクトリでterraform applyを実行

# 再現環境
ローカルでのterraform実行時

# このバグによって引き起こされる問題
SESのリソースを作成することができない

**Comment by kobayashi-m42** [comment]
@keitakn リソース名を修正してSESを構築し直しただけだから、1かな？

**Comment by keitakn** [comment]
@kobayashi-m42 1で大丈夫だと思う！入れておくね！🐱
