### ISSUE TITLE
GitHubActionsにtimeoutを追加する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/kimono-app-terraform#25]
# Doneの定義
表題の件が実施されていること

# 補足情報
https://dev.classmethod.jp/articles/must-set-timeout-on-actions-for-save-cost/

**Comment by keitakn** [comment]
@kobayashi-m42 作成ありがとう！
見た感じストーリーポイント1か2で行けそうな気がするね🐈

**Comment by kobayashi-m42** [comment]
@keitakn 1で大丈夫だと思う！設定しておくね！
