### ISSUE TITLE
CognitoUserPoolからCustomScopeの設定を削除

### ISSUE THREAD

**Issue by keitakn** [nekochans/kimono-app-terraform#30]
# Doneの定義
- CognitoUserPoolからCustomScopeが削除されている事

# 補足情報
- https://github.com/nekochans/kimono-app-frontend/issues/27#issuecomment-682616617 で書いたようにCustomScopeを使わない方向になったので、CustomScopeの設定を削除する。

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイントは2でいいかな🐱？

**Comment by kobayashi-m42** [comment]
@keitakn うん！2で問題ないと思う！
