### ISSUE TITLE
Dockerのterraform環境でTerraform Registoryからmoduleをダウンロードできない

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/kimono-app-terraform#31]
# 概要
Dockerのterraform環境でTerraform Registoryからmoduleだダウンロードできない

# 再現手順
Dockerコンテナに入り下記を実行
```
cd providers/aws/environments/stg/10-network/
terraform init
```

# 再現環境
Docker

# 補足情報
Dockerにgitが追加されていないため、エラーが発生する

**Comment by kobayashi-m42** [comment]
@keitakn ポイントは1かな？

**Comment by keitakn** [comment]
@kobayashi-m42 課題作成ありがとう！1で大丈夫だと思う👍
