### ISSUE TITLE
apiのCI/CD用のIAMユーザを作成する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/kimono-app-terraform#39]
# Doneの定義
- kimono-app-api のCI/CDを実行するために必要な権限をもったIAMユーザが作成されていること

# 補足情報
- CDは構築していないので、当面はGitHubActionsでCIを実行する際に必要となる

**Comment by kobayashi-m42** [comment]
@keitakn ポイントは2くらいかな？🐱

**Comment by keitakn** [comment]
@kobayashi-m42 作成ありがとう！

どのロールをアタッチするかとか考えると、割と大変そうだから、ストーリーポイント3とかでもいいかも🐱！

**Comment by kobayashi-m42** [comment]
@keitakn 確かに！🐱 3ポイントで設定しておくね！
