### ISSUE TITLE
Terraformのバージョンを 0.14系にバージョンアップを行う

### ISSUE THREAD

**Issue by keitakn** [nekochans/kimono-app-terraform#45]
# Doneの定義
- 表題の件が実施されている事

# 補足情報
https://github.com/nekochans/kimono-app-terraform/issues/38 を実施する前にこちらを実施する。

**Comment by keitakn** [comment]
@kobayashi-m42 これさっき作ろうと思って忘れてた・・・🐱
ストーリーポイント5くらいでいいかな？？

**Comment by kobayashi-m42** [comment]
@keitakn うん、5でいいと思う！0.13へのアップグレードに比べると、作業量は少ないと思う🐱

**Comment by keitakn** [comment]
@kobayashi-m42 ありがとう🐱！なるほど0.13の時よりは作業量少ないんだね👍

**Comment by keitakn** [comment]
# めも

以下の手順に従い実施する🐱

https://www.terraform.io/upgrade-guides/0-14.html
